# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Orange-Market' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Then'
  pod 'RxTexture2'
  pod 'Floaty', '~> 4.2.0'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Alamofire', '~> 5.2'
  pod 'Moya/RxSwift'

  # Pods for Orange-Market

end
